# Interfaces
interfaces: # Interfaces are expected to be configurable, so don't forget the colon at the end of the line
  - mqtt: 
      host: "192.168.15.120"
      port: 1883
      username: ""
      password: ""
      client_id: "opus-server"
  
# Drivers
drivers:
  - sonoff
  - tasmota
