# Basic Configs
name: opus-server

# Interfaces
interfaces: # Interfaces are expected to be configurable, so don't forget the colon at the end of the line
  - mqtt<local>: 
      log_id: "mqtt<local>"
      host: "192.168.15.120"
      port: 1883
      username: ""
      password: ""
      client_id: "opus-server"

  - mqtt<maestro>:
      log_id: "mqtt<maestro>"
      host: "144.22.195.55"
      port: 1883
      username: ""
      password: ""
      client_id: "opus-server"
  
# Drivers
drivers:
  - sonoff
  - tasmota
